// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuSYr9xcrniohQxFeNm1MrI2O397DQzg',
    appId: '1:1003218013364:web:14f58edce3a89251da1be1',
    messagingSenderId: '1003218013364',
    projectId: 'projectcv-d60a1',
    authDomain: 'projectcv-d60a1.firebaseapp.com',
    storageBucket: 'projectcv-d60a1.appspot.com',
    measurementId: 'G-9ZN2BPGQBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANpyKpjexeDlDD463tnkc9og5ihfP4zsQ',
    appId: '1:1003218013364:android:4f863eb44ed0d6d3da1be1',
    messagingSenderId: '1003218013364',
    projectId: 'projectcv-d60a1',
    storageBucket: 'projectcv-d60a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23I8Gf_1Mr9OcAWEHtBLIR7qL0wsv4HQ',
    appId: '1:1003218013364:ios:1358d3b48c2cc2f2da1be1',
    messagingSenderId: '1003218013364',
    projectId: 'projectcv-d60a1',
    storageBucket: 'projectcv-d60a1.appspot.com',
    iosClientId: '1003218013364-2ecq6umr53jfkvdu06l5icpco19on591.apps.googleusercontent.com',
    iosBundleId: 'ham.com.active.cvproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD23I8Gf_1Mr9OcAWEHtBLIR7qL0wsv4HQ',
    appId: '1:1003218013364:ios:1358d3b48c2cc2f2da1be1',
    messagingSenderId: '1003218013364',
    projectId: 'projectcv-d60a1',
    storageBucket: 'projectcv-d60a1.appspot.com',
    iosClientId: '1003218013364-2ecq6umr53jfkvdu06l5icpco19on591.apps.googleusercontent.com',
    iosBundleId: 'ham.com.active.cvproject',
  );
}
